### ISSUE TITLE
Main Features Checklist

### ISSUE THREAD

**Issue by Lamby777** [Lamby777/yx#1]
Checklist of important subcommands to add before focusing on smaller features:

- [x] `yx create`
- [x] `yx create <path>`
- [x] `yx list`
- [x] `yx list valid`
- [x] `yx list missing`
- [ ] `yx list by <tag>`
- [x] `yx la`
- [x] `yx la <sort-mode>`
- [ ] `yx clean`
- [x] `yx mv <old> <new>`
- [x] `yx mvt <old> <new>`
- [x] `yx cp <old> <new>`
- [x] `yx cpt <old> <new>`
- [x] `yx apt<old> <new>`
- [x] `yx mapt <old> <new>`
- [x] `yx purge`
- [x] `yx purge yes`
- [x] `yx add <file> <tag>`
- [x] `yx rm <file> <tag>`
- [ ] `yx register <file>`
- [ ] `yx rall`
- [ ] `yx rall <path>`
- [ ] `yx rfits <path>`
- [ ] `yx constraint <constraint>`
- [ ] `yx free`
- [ ] `yx blanket <tag>`
- [ ] `yx forget <tag>`
- [ ] `yx render`
- [ ] `yx render named`
- [ ] `yx render copy`
- [ ] `yx render copy named`
- [x] `yx scribe`
- [ ] `yx scribe <path>` (probably completed, but not tested)
- [x] `yx ignore <path>`
- [x] `yx unignore <path>`
- [x] `yx ilist`

**Comment by Lamby777** [comment]
posted this on https://github.com/Lamby777/brainfuck-rs first by accident :skull:

**Comment by Lamby777** [comment]
Constraints (`constraint` and `free`) will probably be the last thing I work on, because you can just `yx render name` and use your OS's search function to find stuff, and the command is for pretty niche use cases besides that.
Also, `yx clean` would be pretty cool, but that's also low priority for now. Gonna focus on the `list`s, `purge`, and `render`.

**Comment by Lamby777** [comment]
mb, can't even click the right button rn. I'm gonna go to sleep instead of writing more clumsy broken code.

**Comment by Lamby777** [comment]
"List by" seems pretty simple to implement, but that's low priority for now because it's essentially just previewing what `yx constraint <term>` and `yx list` after that would do.

Gonna start work on `purge` and `mv` now.

**Comment by Lamby777** [comment]
Also, there's a readme now to explain a bit better what most of these commands does. The ones not in there are either self-explanatory (like `rm`), too niche (`blanket` and `forget`), or important, but being added later (`mv`).

**Comment by Lamby777** [comment]
`mv` and `purge` added, but now I want to add a way to copy stuff as well...

**Comment by Lamby777** [comment]
Thanks to `sub::retrieve_where`, implementing a "clean" command should be pretty easy now...

**Comment by Lamby777** [comment]
Possibly making `yx add <file>` an alias to `yx register <file>` later, but I'm still keeping `yx register <file>` because that's the only way to register multiple files at once (`yx add` will assume the next arguments are tags, not second files)

Also, maybe there should be a more complicated command for adding multiple tags to multiple files at once?
Could be its own TUI

**Comment by Lamby777** [comment]
`yx scribe` is complete. I keep adding new features to this list and then ticking them off, but hey, at least the completion % is slowly going up. We'll eventually get there.

**Comment by Lamby777** [comment]
Really busy with school, P/E/T/S, and Sparklet. Probably not coming back to this anytime soon, but maybe someday...
